---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: node-test
  name: node-test
spec:
  replicas: 2
  selector:
    matchLabels:
      run: node-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: node-test
    spec:
      containers:
      - image: mandiwal/nicknode:nicknodeTAG
        name: node-test
        imagePullPolicy: Never
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: node-test
  name: node-test
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    #nodePort: 30080
  selector:
    run: node-test
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: node-test
            servicePort: 3000
          